name: CI

on: [push, pull_request]

env:
  SERVER_TAG: docker.pkg.github.com/eclipse/openvsx/server
  SERVER_VERSION: snapshot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Setup Yarn
      run: npm install --global yarn
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/checkout@v2
    - name: Build CLI
      run: yarn --cwd cli
    - name: Build Web UI
      run: |
        yarn --cwd webui
        yarn --cwd webui build:dev
    - name: Build Server
      run: |
        server/gradlew --no-daemon -p server build
        docker build -t $SERVER_TAG:$SERVER_VERSION server
    - name: Push Docker Images
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        docker push $SERVER_TAG:$SERVER_VERSION
