name: CI

on: [push, pull_request]

env:
  NPM_REG: https://npm.pkg.github.com
  SERVER_TAG: docker.pkg.github.com/eclipse/openvsx/server
  SERVER_VERSION: snapshot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Set up Yarn
      run: npm install --global yarn
    - name: Set up Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/checkout@v2
    - name: Build CLI
      run: yarn --cwd cli
    - name: Build Web UI
      run: |
        yarn --cwd webui
        yarn --cwd webui build:dev
    - name: Build Server
      run: |
        server/gradlew --no-daemon -p server build
        docker build -t $SERVER_TAG:$SERVER_VERSION server
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v1
      with:
        name: openvsx-server
        path: server/build/libs/openvsx-server.jar
    - name: Publish Yarn Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
        yarn --cwd cli --non-interactive --no-git-tag-version --registry $NPM_REG publish
        yarn --cwd webui --non-interactive --no-git-tag-version --registry $NPM_REG publish
      if: github.repository == 'eclipse/openvsx' && github.ref == 'refs/heads/master'
    - name: Push Docker Images
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        docker push $SERVER_TAG:$SERVER_VERSION
      if: github.repository == 'eclipse/openvsx' && github.ref == 'refs/heads/master'
